CREATE VIEW BLOCK_PHASE_REQUEST_DOCUMENT_INSTANCE(IN p_registerId NVARCHAR(36)) AS SELECT
  BH_3.BLOCK_ID,
  BH_3.MASTER_BLOCK_ID,
  PH_2.PHASE_ID,
  PH_2.MASTER_PHASE_ID,
  RH_0.REQUEST_ID,
  RH_0.REQUEST_TYPE,
  RH_0.PROCESS_ID,
  RH_0.COUNTRY_ID,
  RH_0.SITE_ID,
  P_1.PROCESS_ID_PK,
  DPB_4.GENERIC_TYPE_ID
FROM (((((REQUEST_HEAD AS RH_0 INNER JOIN PROCESS AS P_1 ON P_1.ID_PK = RH_0.PROCESS_ID) INNER JOIN PHASE_HEAD AS PH_2 ON PH_2.REQUEST_ID = RH_0.REQUEST_ID) INNER JOIN BLOCK_HEAD AS BH_3 ON BH_3.PHASE_ID = PH_2.PHASE_ID) INNER JOIN DOCUMENTS_PER_BLOCK AS DPB_4 ON DPB_4.BLOCK_ID = BH_3.BLOCK_ID) INNER JOIN INSTANCES_PER_DOCUMENT AS IPD_5 ON IPD_5.INSTANCE_ID = DPB_4.REGISTER_ID)
WHERE IPD_5.REGISTER_ID = :P_REGISTERID;
