CREATE VIEW BLOCK_SUPPORT_DOCUMENTS(IN p_blockId NVARCHAR(36)) AS SELECT
  dd_3.REGISTER_ID AS ID,
  dd_3.BLOCK_ID AS blockId,
  dd_3.INSTANCE_ID AS instanceId,
  dd_3.REQUEST_ID AS requestId,
  dd_3.REQUEST_CODE AS requestCode,
  dd_3.TYPE_ID AS docType,
  dd_3.STEP_ID AS stepId,
  dd_3.FIELD AS field,
  dd_3.DOCUMENT_NAME AS documentName,
  dd_3.DOCUMENT_VERSION AS version,
  dd_3.DOCUMENT_URL AS fileUrl,
  dd_3.USER_DOC AS "USER",
  dd_3.CREATION_DATE_DOC AS documentCreationDate,
  dd_3.DOCUMENT_SUBTYPE AS subType,
  dd_3.DOCUMENT_SUBTYPE_LVL2 AS subTypeLvl2,
  dd_3.CREATEDAT AS createdAt,
  dd_3.CREATEDBY AS createdBy,
  dd_3.DELETED AS deleted,
  dd_3.DELETED_BY AS deletedBy,
  dd_3.MODIFIEDAT AS modifiedAt,
  dd_3.MODIFIEDBY AS modifiedBy,
  dd_3.DOCUMENT_ID AS documentId,
  dd_3.OT_DOCUMENT_ID AS OTDocumentId,
  dd_3.BLOCK_NAME AS blockName,
  dd_3.PHASE_NAME AS phaseName,
  dd_3.FINAL_DOCUMENT AS finalDocument,
  dd_3.MEDIA_TYPE AS mediaType,
  dd_3.WORK_ID AS workId,
  CASE WHEN bh_0.BLOCK_STATUS = 7 THEN TRUE ELSE FALSE END AS canDelete,
  NULL AS content
FROM ((((BLOCK_HEAD AS bh_0 INNER JOIN PHASE_HEAD AS ph_1 ON ph_1.PHASE_ID = bh_0.PHASE_ID AND bh_0.BLOCK_ID = :P_BLOCKID) INNER JOIN REQUEST_HEAD AS rh_2 ON rh_2.REQUEST_ID = ph_1.REQUEST_ID) INNER JOIN WF_DETAIL_DOCUMENTS AS dd_3 ON dd_3.BLOCK_ID = bh_0.BLOCK_ID) INNER JOIN DOCUMENT_FLOWS AS df_4 ON df_4.documentId = dd_3.DOCUMENT_ID AND df_4.countryId = rh_2.COUNTRY_ID AND df_4.enableAttachments = TRUE);
