CREATE VIEW BLOCK_PHASE_REQUEST(IN p_blockId NVARCHAR(36)) AS SELECT
  bh_0.BLOCK_ID,
  bh_0.MASTER_BLOCK_ID,
  bh_0.BLOCK_STATUS,
  ph_1.PHASE_ID,
  ph_1.MASTER_PHASE_ID,
  rh_2.REQUEST_ID,
  rh_2.REQUEST_TYPE,
  rh_2.REQUEST_CODE,
  rh_2.PROCESS_ID,
  rh_2.COUNTRY_ID,
  rh_2.SITE_ID,
  rh_2.REQUEST_STATUS,
  p_3.PROCESS_ID_PK,
  bh_0.ROLE_ID
FROM (((BLOCK_HEAD AS bh_0 INNER JOIN PHASE_HEAD AS ph_1 ON ph_1.PHASE_ID = bh_0.PHASE_ID AND bh_0.BLOCK_ID = :P_BLOCKID) INNER JOIN REQUEST_HEAD AS rh_2 ON rh_2.REQUEST_ID = ph_1.REQUEST_ID) INNER JOIN PROCESS AS p_3 ON p_3.ID_PK = rh_2.PROCESS_ID);
