CREATE VIEW CONFIRM_BUTTONS(IN p_requestId NVARCHAR(36), IN p_master_phase_id NVARCHAR(5000), IN p_master_block_id NVARCHAR(5000)) AS SELECT
  bp_3.BTTN_INV_UPDATED,
  bp_3.BTTN_SERV_UPDATED,
  bp_3.BTTN_DOC_UPDATED
FROM ((((REQUEST_HEAD AS rh_0 INNER JOIN PHASE_HEAD AS ph_1 ON ph_1.REQUEST_ID = :P_REQUESTID AND ph_1.MASTER_PHASE_ID = :P_MASTER_PHASE_ID) INNER JOIN BLOCK_HEAD AS bh_2 ON bh_2.PHASE_ID = ph_1.PHASE_ID AND bh_2.MASTER_BLOCK_ID = :P_MASTER_BLOCK_ID) INNER JOIN BLOCKS_PROVISIONING AS bp_3 ON bp_3.BLOCK_ID = bh_2.BLOCK_ID) INNER JOIN PROCESS AS p_4 ON p_4.ID_PK = rh_0.PROCESS_ID);
