CREATE VIEW GET_BLOCK_ID_FROM_MASTERBLOCK_ID(IN p_requestId NVARCHAR(5000), IN p_masterBlockId NVARCHAR(5000)) AS SELECT
  bh_2.BLOCK_ID
FROM ((REQUEST_HEAD AS rh_0 INNER JOIN PHASE_HEAD AS ph_1 ON ph_1.REQUEST_ID = rh_0.REQUEST_ID) INNER JOIN BLOCK_HEAD AS bh_2 ON bh_2.PHASE_ID = ph_1.PHASE_ID)
WHERE rh_0.REQUEST_ID = :P_REQUESTID AND bh_2.MASTER_BLOCK_ID = :P_MASTERBLOCKID;
