CREATE VIEW LAST_ACTIVE_PHASES(IN p_requestId NVARCHAR(36)) AS SELECT
  max(p_2."ORDER") AS LAST_PHASE
FROM ((REQUEST_HEAD AS rh_0 INNER JOIN PHASE_HEAD AS ph_1 ON ph_1.REQUEST_ID = rh_0.REQUEST_ID AND ph_1.REQUEST_ID = :P_REQUESTID AND (ph_1.PHASE_STATUS = 7 OR ph_1.PHASE_STATUS = 3)) INNER JOIN PHASE AS p_2 ON p_2.PHASE_ID = ph_1.MASTER_PHASE_ID AND p_2.ID_PK = rh_0.PROCESS_ID);
