CREATE VIEW project_firstInprogressPhase(IN p_requestId NVARCHAR(36)) AS SELECT
  FIRST_INPROGRESS_PHASE_0.MASTER_PHASE_ID AS processFlowId
FROM FIRST_INPROGRESS_PHASE(p_requestId => :P_REQUESTID) AS FIRST_INPROGRESS_PHASE_0;
