CREATE VIEW project_lastActivePhases(IN p_requestId NVARCHAR(36)) AS SELECT
  LAST_ACTIVE_PHASES_0.LAST_PHASE AS lastPhase
FROM LAST_ACTIVE_PHASES(p_requestId => :P_REQUESTID) AS LAST_ACTIVE_PHASES_0;
