CREATE VIEW REQUEST_ALL_DOCUMENTS(IN p_requestId NVARCHAR(36)) AS SELECT
  dp_3.REGISTER_ID,
  dp_3.GENERIC_TYPE_ID,
  bh_2.MASTER_BLOCK_ID,
  ph_1.MASTER_PHASE_ID,
  rh_0.REQUEST_ID
FROM (((REQUEST_HEAD AS rh_0 INNER JOIN PHASE_HEAD AS ph_1 ON ph_1.REQUEST_ID = :P_REQUESTID AND rh_0.REQUEST_ID = :P_REQUESTID) INNER JOIN BLOCK_HEAD AS bh_2 ON bh_2.PHASE_ID = ph_1.PHASE_ID) INNER JOIN DOCUMENTS_PER_BLOCK AS dp_3 ON dp_3.BLOCK_ID = bh_2.BLOCK_ID AND (dp_3.DELETED IS NULL OR dp_3.DELETED = FALSE));
