CREATE VIEW SINGLE_REQUEST_PROCESS(IN p_requestId NVARCHAR(36)) AS SELECT
  rh_0.REQUEST_ID,
  rh_0.PROCESS_ID,
  rh_0.REQUEST_CODE,
  pr_1.ID_PK,
  pr_1.PROCESS_ID_PK,
  ph_2.PHASE_ID,
  ph_2."ORDER" AS PHASE_ORDER,
  ph_2.NOT_REQUIRED,
  ph_2.ALWAYS_ON,
  ph_2.PASS_OVER,
  ph_2.SKIP_RULE,
  ph_2.CLOSE_BLOCK,
  ph_2.HAS_CANDIDATES,
  bl_3.BLOCK_ID_PK,
  bl_3.VISIBLE_ON,
  bl_3.MANDATORY,
  bl_3.ACTIVE,
  bl_3.ROLE_ID,
  bl_3.HASRESPONSIBLE,
  bl_3.APPROVER_TYPE,
  bl_3.SUBCONTRACTOR_TYPE,
  bl_3.IS_CANDIDATE
FROM (((REQUEST_HEAD AS rh_0 INNER JOIN PROCESS AS pr_1 ON pr_1.ID_PK = rh_0.PROCESS_ID) INNER JOIN PHASE AS ph_2 ON ph_2.ID_PK = rh_0.PROCESS_ID) INNER JOIN BLOCK AS bl_3 ON bl_3.ID_PK = rh_0.PROCESS_ID AND bl_3.PHASE_ID_PK = ph_2.PHASE_ID)
WHERE rh_0.REQUEST_ID = :P_REQUESTID
ORDER BY ph_2."ORDER", bl_3."ORDER";
