CREATE VIEW USERS(IN p_country NVARCHAR(5000)) AS SELECT
  USERS_0.USER_ID AS userId,
  USERS_0.USER_NAME AS userName,
  USERS_0.EMAIL AS email,
  USERS_0.TELEPHONE AS telephone,
  COUNTRIES_1.COUNTRY_ID AS country,
  ROLES_3.IAS_GROUP AS iasGroup,
  '' AS requestId,
  '' AS blockId
FROM (((US_USERS_IAS AS USERS_0 INNER JOIN US_COUNTRIES AS COUNTRIES_1 ON COUNTRIES_1.USER_ID = USERS_0.USER_ID AND COUNTRIES_1.COUNTRY_ID = :P_COUNTRY) INNER JOIN US_BUKS AS BUKS_2 ON BUKS_2.USER_ID = USERS_0.USER_ID) INNER JOIN US_ROLES_AGR AS ROLES_3 ON ROLES_3.USER_ID = USERS_0.USER_ID);
