CREATE VIEW WORKS_BLOCK_PHASE_REQUEST(IN p_workId NVARCHAR(36)) AS SELECT
  gt_0.ID AS WORK_ID,
  gt_0.type_ID AS TYPE,
  gt_0.status AS STATUS,
  bh_1.BLOCK_ID,
  bh_1.MASTER_BLOCK_ID,
  bh_1.BLOCK_STATUS,
  ph_2.PHASE_ID,
  ph_2.MASTER_PHASE_ID,
  rh_3.REQUEST_ID,
  rh_3.REQUEST_TYPE,
  rp_4.PROJECT_OBJECTIVE,
  rh_3.PROCESS_ID,
  rh_3.COUNTRY_ID,
  rh_3.SITE_ID,
  p_5.PROCESS_ID_PK,
  bh_1.ROLE_ID
FROM (((((WORKS AS gt_0 INNER JOIN BLOCK_HEAD AS bh_1 ON bh_1.BLOCK_ID = gt_0.parentId AND gt_0.parentType_ID = 30 AND gt_0.ID = :P_WORKID) INNER JOIN PHASE_HEAD AS ph_2 ON ph_2.PHASE_ID = bh_1.PHASE_ID) INNER JOIN REQUEST_HEAD AS rh_3 ON rh_3.REQUEST_ID = ph_2.REQUEST_ID) INNER JOIN REQUEST_CHAR_PRO AS rp_4 ON rp_4.REQUEST_ID = rh_3.REQUEST_ID) INNER JOIN PROCESS AS p_5 ON p_5.ID_PK = rh_3.PROCESS_ID);
