-- Seed the local mocked-auth user FRPRCOLMNG into the cnx_external identity stubs
-- so srv/utils/userInfo.js can resolve country/companies/roles for the per-request
-- user bootstrap (srv/code/users.js -> currentUserDetails). All REQUEST_HEAD rows
-- in the local HANA replica are country GB, so we attach this user to GB.

DELETE FROM "INTPROJ"."US_USERS_IAS" WHERE USER_ID = 'FRPRCOLMNG';
INSERT INTO "INTPROJ"."US_USERS_IAS" (USER_ID, USER_NAME, EMAIL, TELEPHONE, NEDAP, ILOQ, CARD_NUMBER)
VALUES ('FRPRCOLMNG', 'FR PR COL MNG', 'frprcolmng@local.test', NULL, NULL, NULL, NULL);

DELETE FROM "INTPROJ"."US_COUNTRIES" WHERE USER_ID = 'FRPRCOLMNG';
INSERT INTO "INTPROJ"."US_COUNTRIES" (USER_ID, COUNTRY_ID) VALUES ('FRPRCOLMNG', 'GB');

DELETE FROM "INTPROJ"."US_BUKS" WHERE USER_ID = 'FRPRCOLMNG';
INSERT INTO "INTPROJ"."US_BUKS" (USER_ID, BUK) VALUES ('FRPRCOLMNG', 'GB01');

DELETE FROM "INTPROJ"."US_ROLES_AGR" WHERE USER_ID = 'FRPRCOLMNG';
INSERT INTO "INTPROJ"."US_ROLES_AGR" (USER_ID, IAS_GROUP) VALUES ('FRPRCOLMNG', 'TIS_WF_PRO_ColocationMgr');
INSERT INTO "INTPROJ"."US_ROLES_AGR" (USER_ID, IAS_GROUP) VALUES ('FRPRCOLMNG', 'TIS_WF_PRO_IntProjectsMgr');
INSERT INTO "INTPROJ"."US_ROLES_AGR" (USER_ID, IAS_GROUP) VALUES ('FRPRCOLMNG', 'TIS_Cellnex');
INSERT INTO "INTPROJ"."US_ROLES_AGR" (USER_ID, IAS_GROUP) VALUES ('FRPRCOLMNG', 'TIS_Overview_IntProjects');
